export type FinancialYearFormat = {
  value: string;
  label: string;
  startMonth: number;
  endMonth: number;
};

export type CountryMeta = {
  countryName: string;
  currency: string;
  currencyName: string;
  symbol: string;
};

export const COUNTRIES: CountryMeta[] = [
  {
    countryName: "India",
    currency: "INR",
    currencyName: "Rupee",
    symbol: "Rs",
  },
  {
    countryName: "Saudi Arabia",
    currency: "SAR",
    currencyName: "Riyal",
    symbol: "SAR",
  },
  {
    countryName: "United Arab Emirates",
    currency: "AED",
    currencyName: "Dirham",
    symbol: "AED",
  },
  {
    countryName: "Iraq",
    currency: "IQD",
    currencyName: "Dinar",
    symbol: "IQD",
  },
  {
    countryName: "Iran",
    currency: "IRR",
    currencyName: "Rial",
    symbol: "IRR",
  },
  {
    countryName: "Jordan",
    currency: "JOD",
    currencyName: "Dinar",
    symbol: "JOD",
  },
  {
    countryName: "Lebanon",
    currency: "LBP",
    currencyName: "Pound",
    symbol: "LBP",
  },
  {
    countryName: "Syria",
    currency: "SYP",
    currencyName: "Pound",
    symbol: "SYP",
  },
  {
    countryName: "Israel",
    currency: "ILS",
    currencyName: "Shekel",
    symbol: "ILS",
  },
  {
    countryName: "Palestine",
    currency: "ILS",
    currencyName: "Shekel",
    symbol: "ILS",
  },
  {
    countryName: "Kuwait",
    currency: "KWD",
    currencyName: "Dinar",
    symbol: "KWD",
  },
  {
    countryName: "Qatar",
    currency: "QAR",
    currencyName: "Riyal",
    symbol: "QAR",
  },
  {
    countryName: "Oman",
    currency: "OMR",
    currencyName: "Rial",
    symbol: "OMR",
  },
  {
    countryName: "Bahrain",
    currency: "BHD",
    currencyName: "Dinar",
    symbol: "BHD",
  },
  {
    countryName: "Yemen",
    currency: "YER",
    currencyName: "Rial",
    symbol: "YER",
  },
];

export const INDIA_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

export const INDUSTRIES = [
  "Wholesale Trading",
  "Retail Trading",
  "Import & Export",
  "Distribution / Dealers",
  "E-commerce / Online Trading",
  "IT Services",
  "Web Design & Development",
  "Cyber Security Services",
  "Hardware & Networking",
  "Construction Companies",
  "Pharmaceutical Manufacturing",
  "Food Manufacturing",
  "Textile / Garment Manufacturing",
  "Chemical Manufacturing",
  "Plastic Manufacturing",
  "Steel / Metal Manufacturing",
  "Furniture Manufacturing",
  "Building Contractors",
  "Real Estate Developers",
  "Electrical Equipment Manufacturing",
  "Electronics Manufacturing",
  "Automobile Manufacturing",
  "Hospitals",
  "Clinics",
  "Medical Laboratories",
  "Medical Equipment Suppliers",
  "Pharmacies / Medical Stores",
  "Interior Design",
  "Vehicle Dealers",
  "Automobile Service Centres",
  "Insurance Companies",
  "Chartered Accountants / Audit Firms",
  "Tax Consultants",
  "Schools",
  "Colleges",
  "Training Institutes",
  "Coaching Centers",
  "Educational Consultants",
  "Software Development",
  "Restaurants / Cafes",
  "Travel Agencies",
  "Tourism Operators",
  "Advertising & Marketing Agencies",
  "Event Management",
  "Security Services",
  "Cleaning / Facility Management",
  "NGOs / Non-Profit Organizations",
  "Government Organizations",
  "Property Management",
  "Spare Parts Dealers",
  "Transport & Logistics",
  "Banks",
  "Finance Companies",
  "Hotels & Resorts",
];

export const FINANCIAL_YEAR_FORMATS: FinancialYearFormat[] = [
  { value: "april-march", label: "April - March", startMonth: 4, endMonth: 3 },
  {
    value: "january-december",
    label: "January - December",
    startMonth: 1,
    endMonth: 12,
  },
  {
    value: "february-january",
    label: "February - January",
    startMonth: 2,
    endMonth: 1,
  },
  {
    value: "march-february",
    label: "March - February",
    startMonth: 3,
    endMonth: 2,
  },
  { value: "may-april", label: "May - April", startMonth: 5, endMonth: 4 },
  { value: "june-may", label: "June - May", startMonth: 6, endMonth: 5 },
  { value: "july-june", label: "July - June", startMonth: 7, endMonth: 6 },
  {
    value: "august-july",
    label: "August - July",
    startMonth: 8,
    endMonth: 7,
  },
  {
    value: "september-august",
    label: "September - August",
    startMonth: 9,
    endMonth: 8,
  },
];
